spring.application.name=TheListBackend

# Puerto del servidor
server.port=8080

# Configuracion de base de datos H2 (En memoria)
spring.datasource.url=jdbc:h2:mem:thelistdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Habilitar consola de H2 en http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
